### ISSUE TITLE
Failed to find hip-config.cmake on master

### ISSUE THREAD

**Issue by Dekken** [ROCmSoftwarePlatform/pytorch#361]
```
***** Library versions from cmake find_package *****

rocrand VERSION: 1.8.2
hiprand VERSION: 1.8.2
CMake Error at /usr/share/cmake-3.12/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
  By not providing "Findhip.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "hip", but
  CMake did not find one.

  Could not find a package configuration file provided by "hip" with any of
  the following names:

    hipConfig.cmake
    hip-config.cmake

  Add the installation prefix of "hip" to CMAKE_PREFIX_PATH or set "hip_DIR"
  to a directory containing one of the above files.  If "hip" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /opt/rocm/rocblas/lib/cmake/rocblas/rocblas-config.cmake:89 (find_dependency)
  cmake/public/LoadHIP.cmake:117 (find_package)
  cmake/public/LoadHIP.cmake:154 (find_package_and_print_version)
  cmake/Dependencies.cmake:785 (include)
  CMakeLists.txt:230 (include)
```

```
philix@ws156:~/git/rocm_pt$ locate hip-config
/opt/rocm/hip/lib/cmake/hip/hip-config-version.cmake
/opt/rocm/hip/lib/cmake/hip/hip-config.cmake
```

**Comment by Delaunay** [comment]
Do you have the `rocm-cmake` package installed ?

**Comment by Dekken** [comment]
I didn't, but it doesn't appear to make any difference

**Comment by iotamudelta** [comment]
@Dekken are you building directly on your host or within our docker images?

**Comment by Dekken** [comment]
Host

**Comment by iotamudelta** [comment]
could you give me `ls -l /opt/rocm/hip/cmake/` ?

**Comment by Dekken** [comment]
```
philix@ws156:~$ ls -l /opt/rocm/hip/cmake/
total 32
drwxr-xr-x 2 root root  4096 Feb  6 20:48 FindHIP
-rw-r--r-- 1 root root 25425 Jan 23 10:16 FindHIP.cmake
```

**Comment by iotamudelta** [comment]
With the caveat that I do not recommend you do this on your host as it changes the ROCm installation, this should help:

``
sed -i 's/find_dependency(hip)/find_dependency(HIP)/g' /opt/rocm/rocsparse/lib/cmake/rocsparse/rocsparse-config.cmake
    sed -i 's/find_dependency(hip)/find_dependency(HIP)/g' /opt/rocm/rocfft/lib/cmake/rocfft/rocfft-config.cmake
    sed -i 's/find_dependency(hip)/find_dependency(HIP)/g' /opt/rocm/miopen/lib/cmake/miopen/miopen-config.cmake
    sed -i 's/find_dependency(hip)/find_dependency(HIP)/g' /opt/rocm/rocblas/lib/cmake/rocblas/rocblas-config.cmake

``

**Comment by Dekken** [comment]
if this is a required change should it not be done through another means?

**Comment by iotamudelta** [comment]
We currently do recommend you do use our docker image where this is correctly setup.

**Comment by Dekken** [comment]
this is not acceptable 

docker is a convolution

**Comment by Dekken** [comment]
please consult @dagamayank

**Comment by Dekken** [comment]
might want to add "rccl" to your list of sed commands

**Comment by Dekken** [comment]
after seding "rccl" too it still fails

**Comment by Delaunay** [comment]
I did not have to sed anything on my end to make it work.
I think you might just have a dependency missing.
This is all the libraries I see when I do cmake:

- rocrand
- hiprand
- rocblas
- miopen
- miopengemm
- rocfft
- rocsparse
- rocm-cmake
- rocm-dev
- rocm-device-lib
- rocm-libs
- hcc
- hip_base
- hip_hcc

**Comment by Dekken** [comment]
```
-- ******** Summary ********
-- General:
--   CMake version         : 3.12.1
--   CMake command         : /usr/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler id       : GNU
--   C++ compiler version  : 8.2.0
--   BLAS                  : MKL
--   CXX flags             :   -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -D_FORCE_INLINES -D_MWAITXINTRIN_H_INCLUDED -D__STRICT_ANSI__ -DUSE_FBGEMM -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -Wno-stringop-overflow
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL;NDEBUG;ONNX_NAMESPACE=onnx_torch;USE_C11_ATOMICS=1;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1
--   CMAKE_PREFIX_PATH     : /home/philix/.pyenv/versions/3.7.2/lib/python3.7/site-packages
--   CMAKE_INSTALL_PREFIX  : /home/philix/git/rocm_pt/torch
-- 
--   TORCH_VERSION         : 1.1.0
--   CAFFE2_VERSION        : 1.1.0
--   BUILD_ATEN_MOBILE     : OFF
--   BUILD_ATEN_ONLY       : OFF
--   BUILD_BINARY          : False
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : True
--     Python version      : 3.7.2
--     Python executable   : /home/philix/.pyenv/versions/3.7.2/bin/python3
--     Pythonlibs version  : 3.7.2
--     Python library      : /home/philix/.pyenv/versions/3.7.2/lib/libpython3.7m.so.1.0
--     Python includes     : /home/philix/.pyenv/versions/3.7.2/include/python3.7m
--     Python site-packages: lib/python3.7/site-packages
--   BUILD_CAFFE2_OPS      : True
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : True
--   USE_ASAN              : OFF
--   USE_CUDA              : False
--   USE_ROCM              : ON
--   USE_EIGEN_FOR_BLAS    : 
--   USE_FBGEMM            : ON
--   USE_FFMPEG            : False
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : False
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : False
--   USE_METAL             : OFF
--   USE_MKL               : ON
--   USE_MKLDNN            : ON
--   USE_NCCL              : OFF
--   USE_RCCL              : True
--   USE_NNPACK            : True
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : False
--   USE_OPENMP            : ON
--   USE_PROF              : OFF
--   USE_QNNPACK           : True
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : True
--     USE_MPI             : OFF
--     USE_GLOO            : ON
--     USE_GLOO_IBVERBS    : OFF
--   Public Dependencies  : Threads::Threads;caffe2::mkl;caffe2::mkldnn
--   Private Dependencies : qnnpack;nnpack;cpuinfo;fbgemm;/usr/lib/x86_64-linux-gnu/libnuma.so;fp16;gloo;aten_op_header_gen;foxi_loader;rt;gcc_s;gcc;dl
-- Configuring incomplete, errors occurred!
See also "/home/philix/git/rocm_pt/build/CMakeFiles/CMakeOutput.log".
See also "/home/philix/git/rocm_pt/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 721, in <module>
    build_deps()
  File "setup.py", line 288, in build_deps
    build_dir='build')
  File "/home/philix/git/rocm_pt/tools/build_pytorch_libs.py", line 242, in build_caffe2
    my_env)
  File "/home/philix/git/rocm_pt/tools/build_pytorch_libs.py", line 222, in run_cmake
    check_call(cmake_args, cwd=build_dir, env=my_env)
  File "/home/philix/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/philix/git/rocm_pt', '-DBUILDING_WITH_TORCH_LIBS=ON', '-DBUILD_BINARY=False', '-DBUILD_CAFFE2_OPS=True', '-DBUILD_PYTHON=True', '-DBUILD_SHARED_LIBS=ON', '-DBUILD_TEST=True', '-DBUILD_TORCH=ON', '-DCAFFE2_STATIC_LINK_CUDA=False', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_CXX_FLAGS= ', '-DCMAKE_C_FLAGS= ', '-DCMAKE_EXE_LINKER_FLAGS=', '-DCMAKE_INSTALL_PREFIX=/home/philix/git/rocm_pt/torch', '-DCMAKE_PREFIX_PATH=/home/philix/.pyenv/versions/3.7.2/lib/python3.7/site-packages', '-DCMAKE_SHARED_LINKER_FLAGS=', '-DINSTALL_TEST=True', '-DNCCL_EXTERNAL=False', '-DNUMPY_INCLUDE_DIR=/home/philix/.local/lib/python3.7/site-packages/numpy/core/include', '-DONNX_ML=False', '-DONNX_NAMESPACE=onnx_torch', '-DPYTHON_EXECUTABLE=/home/philix/.pyenv/versions/3.7.2/bin/python3', '-DPYTHON_INCLUDE_DIR=/home/philix/.pyenv/versions/3.7.2/include/python3.7m', '-DPYTHON_LIBRARY=/home/philix/.pyenv/versions/3.7.2/lib/libpython3.7m.so.1.0', '-DRCCL_INCLUDE_DIR=/opt/rocm/include', '-DRCCL_LIB_DIR=/opt/rocm/lib', '-DRCCL_ROOT_DIR=/opt/rocm/', '-DRCCL_SYSTEM_LIB=/opt/rocm/lib/librccl.so', '-DTHD_SO_VERSION=1', '-DTORCH_BUILD_VERSION=1.1.0a0+e6991ed', '-DUSE_CUDA=False', '-DUSE_DISTRIBUTED=True', '-DUSE_FBGEMM=True', '-DUSE_FFMPEG=False', '-DUSE_LEVELDB=False', '-DUSE_LMDB=False', '-DUSE_MKLDNN=True', '-DUSE_NCCL=False', '-DUSE_NNPACK=True', '-DUSE_NUMPY=True', '-DUSE_OPENCV=False', '-DUSE_QNNPACK=True', '-DUSE_RCCL=True', '-DUSE_ROCM=True', '-DUSE_SYSTEM_EIGEN_INSTALL=OFF', '-DUSE_SYSTEM_NCCL=False', '-DUSE_TENSORRT=False', '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON']' returned non-zero exit status 1.
```

**Comment by iotamudelta** [comment]
@Dekken did you run `python tools/amd_build/build_amd.py` first? With what env variables are you invoking `python setup.py install`?

**Comment by Dekken** [comment]
no, I didn't know that file existed

but it appears to have been a requirement

**Comment by Dekken** [comment]
Am I supposed to install a specific version of "libthrust-dev"?

```/usr/include/thrust/system/cuda/detail/guarded_cuda_runtime_api.h:38:10: fatal error: 'cuda_runtime_api.h' file not found
#include <cuda_runtime_api.h>
         ^~~~~~~~~~~~~~~~~~~~
```

**Comment by Delaunay** [comment]
hip-thrust

https://github.com/ROCmSoftwarePlatform/pytorch/issues/337#issuecomment-467220107

**Comment by Dekken** [comment]
seems ok now

**Comment by iotamudelta** [comment]
@Dekken can you close this issue if this works now? Thanks!
