### ISSUE TITLE
Run detectron2 on AMD cluster

### ISSUE THREAD

**Issue by tonysy** [ROCmSoftwarePlatform/pytorch#677]
Hi, I try to run the detectron2 on the AMD cluster(gfx 906).
The official detectron2 has already supported to build and develop on AMD.

After I successfully compile the detectron2 on the AMD cluster, I'm unable to run the training successfully. The log of software environment and MIOpen is reported here: 
[train_detectron2_log.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/4814495/train_detectron2_log.log)

Software version:
```
[32m[06/22 18:57:01 pluses]: [0mEnvironment info:
---------------------  --------------------------------------------------------------------------------------------------------------------
sys.platform           linux
Python                 3.6.8 (default, Aug 10 2019, 04:11:00) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
numpy                  1.16.4
pluses                 0.1.0 @/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses
Compiler               GCC 7.3
CUDA compiler          HIP 20.12.6
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.5.0a0+4ff3872 @/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch
PyTorch debug build    False
GPU available          True
GPU 0,1,2,3            Device 66a1
ROCM_HOME              /public/software/compiler/rocm/rocm-3.3.0/
Pillow                 5.2.0
torchvision            0.6.0a0+abc1506 @/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torchvision
fvcore                 0.1.1.post20200622
---------------------  --------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - HIP Runtime 20.12.6
  - MIOpen 2.3.0
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=1, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=1, USE_STATIC_DISPATCH=OFF, 
```

When I press ctrl+c, I got this, hope you give some suggestiosn and help, thanks
```
MIOpen Error: /root/driver/MLOpen/src/tmp_dir.cpp:47: Can't execute cd /tmp/miopen-gridwise_convolution_implicit_gemm_v4r4_nchw_kcyx_nkhw.cpp-a13b-b2de-0966-1230; KMOPTLLC="-mattr=+enable-ds128 -amdgpu-enable-global-sgpr-addr --amdgpu-spill-vgpr-to-agpr=0" /opt/rocm-3.3.0/bin/hcc  -std=c++14  -DCK_PARAM_PROBLEM_N=4 -DCK_PARAM_PROBLEM_K=256 -DCK_PARAM_PROBLEM_C=64 -DCK_PARAM_PROBLEM_HI=336 -DCK_PARAM_PROBLEM_WI=200 -DCK_PARAM_PROBLEM_HO=336 -DCK_PARAM_PROBLEM_WO=200 -DCK_PARAM_PROBLEM_Y=1 -DCK_PARAM_PROBLEM_X=1 -DCK_PARAM_PROBLEM_CONV_STRIDE_H=1 -DCK_PARAM_PROBLEM_CONV_STRIDE_W=1 -DCK_PARAM_PROBLEM_CONV_DILATION_H=1 -DCK_PARAM_PROBLEM_CONV_DILATION_W=1 -DCK_PARAM_PROBLEM_IN_LEFT_PAD_H=0 -DCK_PARAM_PROBLEM_IN_LEFT_PAD_W=0 -DCK_PARAM_PROBLEM_IN_RIGHT_PAD_H=0 -DCK_PARAM_PROBLEM_IN_RIGHT_PAD_W=0 -DCK_PARAM_PROBLEM_CONV_DIRECTION_FORWARD=1 -DCK_PARAM_PROBLEM_CONV_DIRECTION_BACKWARD_DATA=0 -DCK_PARAM_PROBLEM_CONV_DIRECTION_BACKWARD_WEIGHT=0 -DCK_PARAM_TUNABLE_BLOCK_SIZE=256 -DCK_PARAM_TUNABLE_GEMM_M_PER_BLOCK=128 -DCK_PARAM_TUNABLE_GEMM_N_PER_BLOCK=128 -DCK_PARAM_TUNABLE_GEMM_K_PER_BLOCK=16 -DCK_PARAM_TUNABLE_GEMM_M_PER_THREAD=4 -DCK_PARAM_TUNABLE_GEMM_N_PER_THREAD=4 -DCK_PARAM_TUNABLE_GEMM_M_LEVEL0_CLUSTER=4 -DCK_PARAM_TUNABLE_GEMM_N_LEVEL0_CLUSTER=4 -DCK_PARAM_TUNABLE_GEMM_M_LEVEL1_CLUSTER=4 -DCK_PARAM_TUNABLE_GEMM_N_LEVEL1_CLUSTER=4 -DCK_PARAM_TUNABLE_GEMM_A_BLOCK_COPY_CLUSTER_LENGTHS_GEMM_K=4 -DCK_PARAM_TUNABLE_GEMM_A_BLOCK_COPY_CLUSTER_LENGTHS_GEMM_M=64 -DCK_PARAM_TUNABLE_GEMM_A_BLOCK_COPY_SRC_DATA_PER_READ_GEMM_K=4 -DCK_PARAM_TUNABLE_GEMM_A_BLOCK_COPY_DST_DATA_PER_WRITE_GEMM_M=2 -DCK_PARAM_TUNABLE_GEMM_B_BLOCK_COPY_CLUSTER_LENGTHS_GEMM_K=8 -DCK_PARAM_TUNABLE_GEMM_B_BLOCK_COPY_CLUSTER_LENGTHS_GEMM_N=32 -DCK_PARAM_TUNABLE_GEMM_B_BLOCK_COPY_SRC_DATA_PER_READ_GEMM_N=4 -DCK_PARAM_TUNABLE_GEMM_B_BLOCK_COPY_DST_DATA_PER_WRITE_GEMM_N=4 -DCK_PARAM_TUNABLE_GEMM_C_THREAD_COPY_DST_DATA_PER_WRITE_GEMM_N1=4 -DCK_PARAM_DEPENDENT_GRID_SIZE=4200 -DCK_THREADWISE_GEMM_USE_AMD_INLINE_ASM=1 -D__HIP_PLATFORM_HCC__=1 -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP32=1 -DMIOPEN_USE_INT8=0 -DMIOPEN_USE_INT8x4=0 -DMIOPEN_USE_BFP16=0 -DMIOPEN_USE_INT32=0 -DMIOPEN_USE_RNE_BFLOAT16=1 -mcpu=gfx906 -Wno-everything -amdgpu-target=gfx906 -mcode-object-v3 -Wno-unused-command-line-argument -I. -isystem /opt/rocm-3.3.0/hip/../include -isystem /opt/rocm-3.3.0/hip/include -isystem /opt/rocm/include -hc -Wl,--enable-new-dtags -hc -L /opt/rocm/lib -Wl,-rpath /opt/rocm/lib -Wl,--whole-archive -hc -fPIC -std=c++14 -isystem /opt/rocm/include -isystem /opt/rocm/include -ldl -hc -fPIC -std=c++14 -isystem /opt/rocm/include -isystem /opt/rocm/include -Wl,--no-whole-archive -ldl -lm -hc -fPIC -std=c++14 -isystem /opt/rocm/include -isystem /opt/rocm/include gridwise_convolution_implicit_gemm_v4r4_nchw_kcyx_nkhw.cpp -o /tmp/miopen-gridwise_convolution_implicit_gemm_v4r4_nchw_kcyx_nkhw.cpp-a13b-b2de-0966-1230/gridwise_convolution_implicit_gemm_v4r4_nchw_kcyx_nkhw.cpp.o
MIOpen(HIP): miopenStatus_t miopenDestroyConvolutionDescriptor(miopenConvolutionDescriptor_t){
MIOpen(HIP): 	convDesc = conv2d, miopenConvolution, miopenPaddingDefault, {0, 0}, {1, 1}, {1, 1}, 
MIOpen(HIP): }
MIOpen(HIP): miopenStatus_t miopenDestroyTensorDescriptor(miopenTensorDescriptor_t){
MIOpen(HIP): 	tensorDesc = 256, 64, 1, 1
MIOpen(HIP): }
MIOpen(HIP): miopenStatus_t miopenDestroyTensorDescriptor(miopenTensorDescriptor_t){
MIOpen(HIP): 	tensorDesc = 4, 256, 336, 200
MIOpen(HIP): }
MIOpen(HIP): miopenStatus_t miopenDestroyTensorDescriptor(miopenTensorDescriptor_t){
MIOpen(HIP): 	tensorDesc = 4, 64, 336, 200
MIOpen(HIP): }
[4m[5m[31mERROR[0m [32m[06/22 19:13:16 ps.engine.train_loop]: [0mException during training:
Traceback (most recent call last):
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/modeling/meta_arch/rcnn.py", line 144, in forward
    features = self.backbone(images.tensor)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/modeling/backbone/fpn.py", line 124, in forward
    bottom_up_features = self.bottom_up(x)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/modeling/backbone/resnet.py", line 421, in forward
    x = stage(x)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/modeling/backbone/resnet.py", line 195, in forward
    out = self.conv3(out)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/layers/wrappers.py", line 94, in forward
    x = super().forward(x)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 346, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: miopenStatusUnknownError
[32m[06/22 19:13:16 ps.engine.hooks]: [0mTotal training time: 0:00:32 (0:00:00 on hooks)
Traceback (most recent call last):
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/tools/train_net.py", line 224, in <module>
    args=(args,),
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/engine/launch.py", line 57, in launch
    main_func(*args)
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/tools/train_net.py", line 185, in main
    return trainer.train()
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/engine/defaults.py", line 422, in train
    super().train(self.start_iter, self.max_iter)
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/modeling/meta_arch/rcnn.py", line 144, in forward
    features = self.backbone(images.tensor)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/modeling/backbone/fpn.py", line 124, in forward
    bottom_up_features = self.bottom_up(x)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/modeling/backbone/resnet.py", line 421, in forward
    x = stage(x)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/modeling/backbone/resnet.py", line 195, in forward
    out = self.conv3(out)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/home/ssct050t/users/zhangsy/projects/dets/pluses/pluses/layers/wrappers.py", line 94, in forward
    x = super().forward(x)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "/public/software/apps/DeepLearning/PyTorch/rocm3.3_torch1.5/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 346, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: miopenStatusUnknownError

```

Discussion is related to https://github.com/ROCmSoftwarePlatform/MIOpen/issues/87#issuecomment-647517646

As I have no root access to install ROCm3.5 with apt or use docker.

**I wonder is there any possibility to install ROCm3.5 and build the pytorch locally by myself.
Or set some environment variables to make the script run successfully with ROCm3.3?**

Thanks

**Comment by sunway513** [comment]
Hi @tonysy , can you firstly try to upgrade your baseline environment to ROCm3.5?
You can follow the instructions here:
https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html
cc @hgaspar  @jeffdaily

**Comment by tonysy** [comment]
@sunway513 Hi, I think it's difficult for me to upgrade the environment from 3.3 to 3.5 in a short time,  because we rent such an AMD GPU cluster and have no root access to finish installation according to your provided guide.(We have contacted the HPC administration and they said it needs to stop all nodes of the cluster and not possible in a short time)

I would like to try to install the ROCm3.5 locally without root access, while I'm not sure it's possible or not. Or other solutions?  

Thanks

**Comment by sunway513** [comment]
Our support for Detectron2 on ROCm3.3 is limited, mainly due to the lack of options to address the high overheads for the MIOpen configurations been called by Detectron2. 
That's why I'd suggest you to go with ROCm3.5 if Detectron2 is required for your project. 

Will it be possible to build and install MIOpen develop branch in your local environment?
If so, that would be helpful as well, as you can at least enable the MIOpen hybrid find mode.

**Comment by tonysy** [comment]
I would like to try "Build and install MIOpen develop branch in your local environment?"
Does it mean to clone the https://github.com/ROCmSoftwarePlatform/MIOpen and build from the source on the AMD GPU node?

**Comment by sunway513** [comment]
Yes, that's correct. You can start from here to build MIOpen from source:
https://github.com/ROCmSoftwarePlatform/MIOpen#installing-minimum-dependencies-in-rocm-environment

**Comment by 401qingkong** [comment]
@sunway513 Hi，I notice the new feature in miopen 2.4. I  wonder to know if I upgrade to the latest miopen version in the local environment, do I need to recompile pytorch from source to link the new miopen library?  And, How to keep and switch multiple miopen versions in use as needed.

**Comment by tonysy** [comment]
@sunway513 Hi, 
I can successfully compile and build the MIOpen 2.4.0 with ROCm3.3. Could you share more about how to use the MIOpen 2.4.0 with ROCm3.3 for the detectron2 project? Thanks a lot.

**Comment by sunway513** [comment]
Hi @tonysy , you can try to set the following environment variable and execute the Detectron2:
`export MIOPEN_FIND_MODE=3`

In addition, make sure you clean up the MIOpen cache folders, since you've upgraded the MIOpen version:
`rm -rf ~/.cache`

**Comment by tonysy** [comment]
@sunway513 Hi, I found though the build process of MIOpen 2.4.0 is successful. There have some issues for the test process.

When I conduct `./MIOpenDriver --version` to check the MIOpenDriver, I get the following erros:

```
>MIOpen-2.4.0/build/bin 21:42:26]$./MIOpenDriver --version
./MIOpenDriver: relocation error: ./MIOpenDriver: symbol _ZN6miopen5debug15FindModeDisableE, version MIOPEN_HIP_1 not defined in file libMIOpen.so.1 with link time reference
```

I have searched the MIOpen repo but don't find solutions. Could you give some hints or ideas? Thanks

I use the 2.4.0 release version of MIOpen and the build command is :
```
CXX=/public/software/compiler/rocm/rocm-3.3.0/bin/hcc \
cmake -DMIOPEN_BACKEND=HIP \
-DCMAKE_PREFIX_PATH="/public/software/compiler/rocm/rocm-3.3.0/hcc;/public/software/compiler/rocm/rocm-3.3.0/hip;/public/home/ssct050t/local_envs" \
-DCMAKE_INSTALL_PREFIX=/public/home/ssct050t/softwares/rocm3.3.0_miopen2.4.0 \
-DBOOST_ROOT=/public/home/ssct050t/local_envs/include/ \
-DBoost_NO_BOOST_CMAKE=ON ..
```

**Comment by sunway513** [comment]
Hi @tonysy , can you create an issue in MIOpen repo and check with the team there:
https://github.com/ROCmSoftwarePlatform/MIOpen/issues
Also, would you confirm with your system admin and see if you can use docker containers in the cluster? Docker container deployment doesn't require sudo access.

**Comment by sunway513** [comment]
Hi @tonysy , the reported issue should have been fixed with ROCm4.2 with MIOPEN_FIND_MODE=5.
